# Generated by Django 4.0.4 on 2022-04-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Development tool',
                'verbose_name_plural': 'Development tools',
            },
        ),
    ]
