# Generated by Django 4.0.4 on 2022-04-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_keyboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='template-images')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'template',
                'verbose_name_plural': 'Templates',
                'ordering': ('-added',),
            },
        ),
    ]
