# Generated by Django 4.0.4 on 2022-05-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_tutorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-added',), 'verbose_name': 'book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='image',
        ),
    ]
