# Generated by Django 4.0.4 on 2022-04-20 18:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='project-images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'projects',
                'verbose_name_plural': 'Projects',
                'ordering': ('-created',),
            },
        ),
    ]
