# Generated by Django 4.0.4 on 2022-04-26 10:33

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Day30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('day', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('body', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.challengename')),
            ],
            options={
                'verbose_name': '30 day',
                'verbose_name_plural': '30 Day challenge',
                'ordering': ('-created',),
            },
        ),
    ]
