# Generated by Django 4.0.4 on 2022-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_project_body_project_url_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day30',
            name='body',
            field=models.FileField(upload_to=''),
        ),
    ]
