# Generated by Django 4.0.4 on 2022-05-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=210)),
                ('description', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='design-images')),
                ('link', models.URLField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-added',),
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='music-images')),
                ('link', models.URLField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'music',
                'verbose_name_plural': 'Musics',
                'ordering': ('-added',),
            },
        ),
    ]
