# Generated by Django 4.0.4 on 2022-04-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=40)),
                ('length', models.IntegerField()),
                ('link', models.URLField()),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'music',
                'verbose_name_plural': 'Musics',
                'ordering': ('-added',),
            },
        ),
    ]
