# Generated by Django 4.0.4 on 2022-04-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='length',
            field=models.FloatField(),
        ),
    ]
