# Generated by Django 4.0.4 on 2022-05-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(default=None, upload_to='music-images'),
            preserve_default=False,
        ),
    ]
